### ISSUE TITLE
java.lang.IllegalArgumentException: Account type cannot be null.

### ISSUE THREAD

**Issue by voltumna** [CAAPIM/Cordova-MAS-SDK#20]
Hello There,
i have tried to use the test apps for cordova but I keep getting

`2021-03-26 14:56:17.032 23550-23550/com.app.bundle.identifier I/ViewRootImpl@f7e1f20[MainActivity]: ViewPostIme pointer 1
2021-03-26 14:56:17.086 23550-27432/com.app.bundle.identifier E/MAS: Failed to load meta-data from the service: ComponentInfo{com.app.bundle.identifier/com.ca.mas.core.storage.sharedstorage.MASAuthenticatorService}
2021-03-26 14:56:17.088 23550-27432/com.app.bundle.identifier E/com.ca.mas.cordova.core.MASPluginMAS: java.lang.reflect.InvocationTargetException
    com.ca.mas.core.datasource.DataSourceException: java.lang.reflect.InvocationTargetException
        at com.ca.mas.core.datasource.DataSourceFactory.getStorage(DataSourceFactory.java:25)
        at com.ca.mas.core.store.StorageProvider.createTokenManager(StorageProvider.java:87)
        at com.ca.mas.core.store.StorageProvider.<init>(StorageProvider.java:41)
        at com.ca.mas.core.store.StorageProvider.getInstance(StorageProvider.java:51)
        at com.ca.mas.core.conf.ConfigurationManager$ClientChangeListener.onUpdated(ConfigurationManager.java:412)
        at com.ca.mas.core.conf.ConfigurationManager.activate(ConfigurationManager.java:176)
        at com.ca.mas.core.conf.ConfigurationManager.activateDefault(ConfigurationManager.java:166)
        at com.ca.mas.core.conf.ConfigurationManager.load(ConfigurationManager.java:160)
        at com.ca.mas.core.conf.ConfigurationManager.getConnectedGatewayConfigurationProvider(ConfigurationManager.java:119)
        at com.ca.mas.foundation.MASConfiguration.getIdTokenSignAlg(MASConfiguration.java:177)
        at com.ca.mas.foundation.MAS.isAlgoRS256(MAS.java:105)
        at com.ca.mas.foundation.MAS.init(MAS.java:100)
        at com.ca.mas.foundation.MAS.start(MAS.java:184)
        at com.ca.mas.cordova.core.MASPluginMAS.start(MASPluginMAS.java:412)
        at com.ca.mas.cordova.core.MASPluginMAS.execute(MASPluginMAS.java:132)
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:206)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.ca.mas.core.datasource.DataSourceFactory.getStorage(DataSourceFactory.java:23)
        at com.ca.mas.core.store.StorageProvider.createTokenManager(StorageProvider.java:87) 
        at com.ca.mas.core.store.StorageProvider.<init>(StorageProvider.java:41) 
        at com.ca.mas.core.store.StorageProvider.getInstance(StorageProvider.java:51) 
        at com.ca.mas.core.conf.ConfigurationManager$ClientChangeListener.onUpdated(ConfigurationManager.java:412) 
        at com.ca.mas.core.conf.ConfigurationManager.activate(ConfigurationManager.java:176) 
        at com.ca.mas.core.conf.ConfigurationManager.activateDefault(ConfigurationManager.java:166) 
        at com.ca.mas.core.conf.ConfigurationManager.load(ConfigurationManager.java:160) 
        at com.ca.mas.core.conf.ConfigurationManager.getConnectedGatewayConfigurationProvider(ConfigurationManager.java:119) 
        at com.ca.mas.foundation.MASConfiguration.getIdTokenSignAlg(MASConfiguration.java:177) 
        at com.ca.mas.foundation.MAS.isAlgoRS256(MAS.java:105) 
        at com.ca.mas.foundation.MAS.init(MAS.java:100) 
        at com.ca.mas.foundation.MAS.start(MAS.java:184) 
        at com.ca.mas.cordova.core.MASPluginMAS.start(MASPluginMAS.java:412) 
        at com.ca.mas.cordova.core.MASPluginMAS.execute(MASPluginMAS.java:132) 
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98) 
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132) 
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59) 
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41) 
        at android.os.MessageQueue.nativePollOnce(Native Method) 
        at android.os.MessageQueue.next(MessageQueue.java:335) 
        at android.os.Looper.loop(Looper.java:206) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
     Caused by: java.lang.IllegalArgumentException: Account type cannot be null.
        at com.ca.mas.core.storage.sharedstorage.AccountManagerUtil.<init>(AccountManagerUtil.java:43)
        at com.ca.mas.core.storage.sharedstorage.MASSharedStorage.getStorageProvider(MASSharedStorage.java:167)
        at com.ca.mas.core.storage.sharedstorage.MASSharedStorage.<init>(MASSharedStorage.java:69)
        at com.ca.mas.core.storage.MASSecureSharedStorage.<init>(MASSecureSharedStorage.java:28)
        at com.ca.mas.core.datasource.MASSecureStorageDataSource.<init>(MASSecureStorageDataSource.java:53)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at com.ca.mas.core.datasource.DataSourceFactory.getStorage(DataSourceFactory.java:23) 
        at com.ca.mas.core.store.StorageProvider.createTokenManager(StorageProvider.java:87) 
        at com.ca.mas.core.store.StorageProvider.<init>(StorageProvider.java:41) 
        at com.ca.mas.core.store.StorageProvider.getInstance(StorageProvider.java:51) 
        at com.ca.mas.core.conf.ConfigurationManager$ClientChangeListener.onUpdated(ConfigurationManager.java:412) 
        at com.ca.mas.core.conf.ConfigurationManager.activate(ConfigurationManager.java:176) 
        at com.ca.mas.core.conf.ConfigurationManager.activateDefault(ConfigurationManager.java:166) 
        at com.ca.mas.core.conf.ConfigurationManager.load(ConfigurationManager.java:160) 
        at com.ca.mas.core.conf.ConfigurationManager.getConnectedGatewayConfigurationProvider(ConfigurationManager.java:119) 
        at com.ca.mas.foundation.MASConfiguration.getIdTokenSignAlg(MASConfiguration.java:177) 
        at com.ca.mas.foundation.MAS.isAlgoRS256(MAS.java:105) 
        at com.ca.mas.foundation.MAS.init(MAS.java:100) 
        at com.ca.mas.foundation.MAS.start(MAS.java:184) 
        at com.ca.mas.cordova.core.MASPluginMAS.start(MASPluginMAS.java:412) 
        at com.ca.mas.cordova.core.MASPluginMAS.execute(MASPluginMAS.java:132) 
        at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98) 
        at org.apache.cordova.PluginManager.exec(PluginManager.java:132) 
        at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59) 
        at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41) 
        at android.os.MessageQueue.nativePollOnce(Native Method) 
        at android.os.MessageQueue.next(MessageQueue.java:335) 
        at android.os.Looper.loop(Looper.java:206) 
        at android.os.HandlerThread.run(HandlerThread.java:67) 
2021-03-26 14:56:17.088 23550-27432/com.app.bundle.identifier W/PluginManager: THREAD WARNING: exec() call to MASPluginMAS.start blocked the main thread for 26ms. Plugin should use CordovaInterface.getThreadPool().
2021-03-26 14:56:17.091 23550-27432/com.app.bundle.identifier E/MAS: Failed to load meta-data from the service: ComponentInfo{com.app.bundle.identifier/com.ca.mas.core.storage.sharedstorage.MASAuthenticatorService}
2021-03-26 14:56:17.093 23550-23550/com.app.bundle.identifier D/InputMethodManager: HSIFW - flag : 0`

Any ideas?
Thanks

Maurizio

**Comment by voltumna** [comment]
OK, I seem to have found the solution, it was quite convoluted but it is related to the article
https://techdocs.broadcom.com/us/en/ca-enterprise-software/layer7-api-management/mobile-sdk-for-ca-mobile-api-gateway/1-8-00/Xamarin/XamarinAndroid_1-8/Create-App-from-Scratch-or-Integrate-an-Existing-App-into-the-Mobile-SDK/Configure-Secure-Account-Manager-Storage.html

and the issue is also shown here
https://community.broadcom.com/communities/community-home/digestviewer/viewthread?MID=802202

With those, I was hinted to a solution
